/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.interfaz;

import java.io.File;
import java.util.Scanner;
import java.util.concurrent.Semaphore;
import javax.swing.Timer;

/**
 *
 * @author rodolfo
 */
public class Interfaz extends javax.swing.JFrame {
           
        
    Archivo a;
    private static int[] vec = new int[19];
       
       
        Almacen neumatico = new Almacen(vec[3],"neumatico");
        Almacen buje = new Almacen(vec[4],"buje");
        Almacen rueda = new Almacen(vec[5],"rueda");
        Almacen marco = new Almacen(vec[6],"marco");

 
;
//      Semaforo
     Semaphore semBuje = new Semaphore(0);
     Semaphore bufferBuje = new Semaphore(vec[4]);
     Semaphore mutexBuje = new Semaphore(1);
      
     Semaphore semNeu = new Semaphore(0);
     Semaphore bufferNeu = new Semaphore(vec[3]);
     Semaphore mutexNeu = new Semaphore(1);
     
     Semaphore semMar = new Semaphore(0);
     Semaphore bufferMar = new Semaphore(vec[6]);
     Semaphore mutexMar = new Semaphore(1);
     
     Semaphore semRueda = new Semaphore(0);
     Semaphore bufferRueda = new Semaphore(vec[5]);
     Semaphore mutexRueda = new Semaphore(1);
     
     int tiempo = vec[0];
     boolean cond = true,cond2 = true;
     int dBuje=tiempo, dNeumatico=tiempo, dMarco=tiempo*2,dRueda =tiempo/2,dBici = tiempo*2,dTriciclo = tiempo*3;
     
     

     //Estructuras tipo Array donde van a correr todos los hilos (asi poder acceder a ellos y modificarlos de forma mas facil)
     Productor vecNeumatico[] = new Productor[vec[11]];
     Productor vecBuje[] = new Productor[vec[12]];
     Mixto vecRueda[] = new Mixto[vec[13]];
     Productor vecMarco[] =  new Productor[vec[14]];
     Consumidor vecBicicleta[] = new Consumidor[vec[17]];
     Consumidor vecTriciclo[] = new Consumidor[vec[18]];
     Tiempo vecTiempo[] = new Tiempo[2];///<----Vector de tiempos de Produccion (Bicicleta - Triciclo)
     
     
  
     
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNeumatico = new javax.swing.JTextField();
        textBuje = new javax.swing.JTextField();
        textRueda = new javax.swing.JTextField();
        textMarco = new javax.swing.JTextField();
        piezaNeumatico = new javax.swing.JTextField();
        piezaBuje = new javax.swing.JTextField();
        piezaRueda = new javax.swing.JTextField();
        piezaMarco = new javax.swing.JTextField();
        playNeu = new javax.swing.JButton();
        agregarNeumatico = new javax.swing.JButton();
        agregarBuje = new javax.swing.JButton();
        agregarRueda = new javax.swing.JButton();
        agregarMarco = new javax.swing.JButton();
        despedirNeumatico = new javax.swing.JButton();
        despedirBuje = new javax.swing.JButton();
        despedirRueda = new javax.swing.JButton();
        despedirMarco = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tiempoGlobal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        playBuje = new javax.swing.JButton();
        playRueda = new javax.swing.JButton();
        playMarco = new javax.swing.JButton();
        pausaNeu = new javax.swing.JButton();
        pausaBuje = new javax.swing.JButton();
        pausaRueda = new javax.swing.JButton();
        pausaMarco = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textBici = new javax.swing.JTextField();
        textTriciclo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tiempoBici = new javax.swing.JTextField();
        tiempoTriciclo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        piezaBicicleta = new javax.swing.JTextField();
        piezaTriciclo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        playBici = new javax.swing.JButton();
        playTriciclo = new javax.swing.JButton();
        pausaBici = new javax.swing.JButton();
        pausaTriciclo = new javax.swing.JButton();
        agregarBicicleta = new javax.swing.JButton();
        despedirBicicleta = new javax.swing.JButton();
        agregarTriciclo = new javax.swing.JButton();
        despedirTriciclo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Productores"));

        jLabel1.setText("Neumaticos");

        jLabel2.setText("Bujes");

        jLabel3.setText("Ruedas");

        jLabel4.setText("Marcos");

        textNeumatico.setEditable(false);
        textNeumatico.setText("                   ");
        textNeumatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNeumaticoActionPerformed(evt);
            }
        });

        textBuje.setEditable(false);
        textBuje.setText("                   ");

        textRueda.setEditable(false);
        textRueda.setText("                   ");

        textMarco.setEditable(false);
        textMarco.setText("                   ");

        piezaNeumatico.setEditable(false);
        piezaNeumatico.setText("                    ");

        piezaBuje.setEditable(false);
        piezaBuje.setText("                    ");

        piezaRueda.setEditable(false);
        piezaRueda.setText("                    ");
        piezaRueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piezaRuedaActionPerformed(evt);
            }
        });

        piezaMarco.setEditable(false);
        piezaMarco.setText("                    ");

        playNeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100045_Play1Disabled.png"))); // NOI18N
        playNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playNeuActionPerformed(evt);
            }
        });

        agregarNeumatico.setText("+");
        agregarNeumatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNeumaticoActionPerformed(evt);
            }
        });

        agregarBuje.setText("+");
        agregarBuje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBujeActionPerformed(evt);
            }
        });

        agregarRueda.setText("+");
        agregarRueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRuedaActionPerformed(evt);
            }
        });

        agregarMarco.setText("+");
        agregarMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMarcoActionPerformed(evt);
            }
        });

        despedirNeumatico.setText("-");
        despedirNeumatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirNeumaticoActionPerformed(evt);
            }
        });

        despedirBuje.setText("-");
        despedirBuje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirBujeActionPerformed(evt);
            }
        });

        despedirRueda.setText("-");
        despedirRueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirRuedaActionPerformed(evt);
            }
        });

        despedirMarco.setText("-");
        despedirMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirMarcoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nro Prod.");

        jLabel6.setText("Piezas");

        jLabel7.setText("Estado");

        tiempoGlobal.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel8.setText("Tiempo Global");

        playBuje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100045_Play1Disabled.png"))); // NOI18N
        playBuje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBujeActionPerformed(evt);
            }
        });

        playRueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100045_Play1Disabled.png"))); // NOI18N
        playRueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playRuedaActionPerformed(evt);
            }
        });

        playMarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100045_Play1Disabled.png"))); // NOI18N
        playMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playMarcoActionPerformed(evt);
            }
        });

        pausaNeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100809_media-playback-pause.png"))); // NOI18N
        pausaNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaNeuActionPerformed(evt);
            }
        });

        pausaBuje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100809_media-playback-pause.png"))); // NOI18N
        pausaBuje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaBujeActionPerformed(evt);
            }
        });

        pausaRueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100809_media-playback-pause.png"))); // NOI18N
        pausaRueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaRuedaActionPerformed(evt);
            }
        });

        pausaMarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100809_media-playback-pause.png"))); // NOI18N
        pausaMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaMarcoActionPerformed(evt);
            }
        });

        jLabel15.setText("Contratar/Despedir");

        start.setText("INICIAR");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textBuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(textNeumatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textRueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textMarco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(piezaNeumatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piezaBuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piezaRueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piezaMarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(playRueda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pausaRueda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(playNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pausaNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playBuje, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(playMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pausaBuje, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(pausaMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(agregarBuje, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(agregarNeumatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(despedirNeumatico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(despedirBuje, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agregarRueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(agregarMarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(despedirMarco, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(despedirRueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(31, 31, 31)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tiempoGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tiempoGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(playNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pausaNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(agregarNeumatico)
                                                    .addComponent(despedirNeumatico))))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textNeumatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(piezaNeumatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(piezaBuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textBuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(playBuje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pausaBuje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(agregarBuje)
                                        .addComponent(despedirBuje)))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pausaRueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(playRueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(piezaRueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textRueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregarRueda)
                                    .addComponent(despedirRueda))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(agregarMarco)
                                .addComponent(jLabel4)
                                .addComponent(textMarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(piezaMarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(despedirMarco)
                            .addComponent(playMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pausaMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ensambladores"));

        jLabel9.setText("Bicicletas");

        jLabel10.setText("Triciclos");

        jLabel11.setText("Nro Ensam.");

        textBici.setEditable(false);

        textTriciclo.setEditable(false);

        jLabel12.setText("Tiempo");

        tiempoBici.setEditable(false);

        tiempoTriciclo.setEditable(false);

        jLabel13.setText("Cant Prod.");

        piezaBicicleta.setEditable(false);

        piezaTriciclo.setEditable(false);
        piezaTriciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piezaTricicloActionPerformed(evt);
            }
        });

        jLabel14.setText("Estado");

        playBici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100045_Play1Disabled.png"))); // NOI18N
        playBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBiciActionPerformed(evt);
            }
        });

        playTriciclo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100045_Play1Disabled.png"))); // NOI18N
        playTriciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playTricicloActionPerformed(evt);
            }
        });

        pausaBici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100809_media-playback-pause.png"))); // NOI18N
        pausaBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaBiciActionPerformed(evt);
            }
        });

        pausaTriciclo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/interfaz/1486100809_media-playback-pause.png"))); // NOI18N
        pausaTriciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaTricicloActionPerformed(evt);
            }
        });

        agregarBicicleta.setText("+");
        agregarBicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBicicletaActionPerformed(evt);
            }
        });

        despedirBicicleta.setText("-");
        despedirBicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirBicicletaActionPerformed(evt);
            }
        });

        agregarTriciclo.setText("+");
        agregarTriciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTricicloActionPerformed(evt);
            }
        });

        despedirTriciclo.setText("-");
        despedirTriciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirTricicloActionPerformed(evt);
            }
        });

        jLabel16.setText("Contratar/Despedir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(textTriciclo)
                    .addComponent(textBici))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tiempoBici, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(tiempoTriciclo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel12)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(piezaTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(piezaBicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel13)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(playBici, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pausaBici, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pausaTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarBicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(despedirBicicleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(despedirTriciclo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel14)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregarTriciclo)
                        .addComponent(despedirTriciclo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(textBici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tiempoBici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(piezaBicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(playBici, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pausaBici, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(despedirBicicleta)
                                .addComponent(agregarBicicleta)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pausaTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tiempoTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(piezaTriciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playMarcoActionPerformed
        for(int i = 0; i < vecMarco.length ; i++){
            if(vecMarco[i]!=null){
            vecMarco[i].setPausa(true);
            }
        }
    }//GEN-LAST:event_playMarcoActionPerformed

    private void playRuedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playRuedaActionPerformed
        for(int i = 0; i < vecRueda.length ; i++){
            if(vecRueda[i]!=null){
            vecRueda[i].setPausa(true);
            }
        }
    }//GEN-LAST:event_playRuedaActionPerformed

    private void playBujeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBujeActionPerformed
        for(int i = 0; i < vecBuje.length ; i++){
            if(vecBuje[i]!=null){
            vecBuje[i].setPausa(true);
            }
        }
    }//GEN-LAST:event_playBujeActionPerformed

    private void agregarBujeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBujeActionPerformed
   
        if(vec[8] < vec[12]){
      
            for(int i = 0 ; i< vecBuje.length ; i++){
                if(vecBuje[i]==null){
                Productor pBuje = new Productor(piezaBuje,buje,bufferBuje,semBuje,mutexBuje,"buje",dBuje);
                vecBuje[i] = pBuje;
                vecBuje[i].start();
                break;
                        }
            }
            int cont = vec[8] + 1;
            vec[8] = vec[8]+1;
            String cantidad = String.valueOf(cont);
            textBuje.setText(cantidad);
        }
    }//GEN-LAST:event_agregarBujeActionPerformed

    private void agregarNeumaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNeumaticoActionPerformed
      
        if(vec[7] < vec[11]){
      
                for(int i = 0 ; i < vecNeumatico.length ; i++){
                    if(vecNeumatico[i]==null){
                        Productor pNeumatico = new Productor(piezaNeumatico,neumatico,bufferNeu,semNeu,mutexNeu,"neumatico",dNeumatico);
                        vecNeumatico[i] = pNeumatico;
                        vecNeumatico[i].start();
                        break;
                        }
            }
      int cont = vec[7] + 1;
      vec[7] = vec[7] + 1;
      String cantidad = String.valueOf(cont);
      textNeumatico.setText(cantidad);
      }
    }//GEN-LAST:event_agregarNeumaticoActionPerformed

    private void playNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playNeuActionPerformed
        for(int i = 0; i < vecNeumatico.length ; i++){
            if(vecNeumatico[i]!=null){
            vecNeumatico[i].setPausa(true);
            }
        }
    }//GEN-LAST:event_playNeuActionPerformed

    private void pausaNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaNeuActionPerformed
        for(int i = 0; i < vecNeumatico.length ; i++){
            if(vecNeumatico[i]!=null){
            vecNeumatico[i].setPausa(false);
            }
        }
    }//GEN-LAST:event_pausaNeuActionPerformed

    private void pausaBujeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaBujeActionPerformed
        for(int i = 0; i < vecBuje.length ; i++){
            if(vecBuje[i]!=null){
            vecBuje[i].setPausa(false);
            }
        }
    }//GEN-LAST:event_pausaBujeActionPerformed

    private void pausaRuedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaRuedaActionPerformed
       for(int i = 0; i < vecRueda.length ; i++){
            if(vecRueda[i]!=null){
            vecRueda[i].setPausa(false);
            }
        }
    }//GEN-LAST:event_pausaRuedaActionPerformed

    private void pausaMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaMarcoActionPerformed
       for(int i = 0; i < vecMarco.length ; i++){
            if(vecMarco[i]!=null){
            vecMarco[i].setPausa(false);
            }
        }
    }//GEN-LAST:event_pausaMarcoActionPerformed

    private void playBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBiciActionPerformed
        for(int i = 0; i < vecBicicleta.length ; i++){
            if(vecBicicleta[i]!=null){
            vecBicicleta[i].setPausa(true);
            }
        }
        vecTiempo[0].setPausa(true);
    }//GEN-LAST:event_playBiciActionPerformed

    private void playTricicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playTricicloActionPerformed
       for(int i = 0; i < vecTriciclo.length ; i++){
            if(vecTriciclo[i]!=null){
            vecTriciclo[i].setPausa(true);
            }
        }
       vecTiempo[1].setPausa(true);
    }//GEN-LAST:event_playTricicloActionPerformed

    private void pausaBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaBiciActionPerformed
        for(int i = 0; i < vecBicicleta.length ; i++){
            if(vecBicicleta[i]!=null){
            vecBicicleta[i].setPausa(false);
            }
        }
        vecTiempo[0].setPausa(false);
    }//GEN-LAST:event_pausaBiciActionPerformed

    private void pausaTricicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaTricicloActionPerformed
        for(int i = 0; i < vecTriciclo.length ; i++){
            if(vecTriciclo[i]!=null){
            vecTriciclo[i].setPausa(false);
            }
        }
        vecTiempo[1].setPausa(false);
    }//GEN-LAST:event_pausaTricicloActionPerformed

    private void piezaTricicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piezaTricicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piezaTricicloActionPerformed

    private void textNeumaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNeumaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNeumaticoActionPerformed

    private void piezaRuedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piezaRuedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piezaRuedaActionPerformed

    private void agregarMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMarcoActionPerformed
        if(vec[10] < vec[14]){
      
            for(int i = 0 ; i< vecMarco.length ; i++){
                if(vecMarco[i]==null){
                Productor pMarco = new Productor(piezaMarco,marco,bufferMar,semMar,mutexMar,"marco",dMarco);
                vecMarco[i] = pMarco;
                vecMarco[i].start();
                break;
                        }
            }
            int cont = vec[10] + 1;
            vec[10] = vec[10] + 1;
            String cantidad = String.valueOf(cont);
            textMarco.setText(cantidad);
        }
        
    }//GEN-LAST:event_agregarMarcoActionPerformed

    private void agregarBicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBicicletaActionPerformed
    
    if(vec[15] < vec[16])    {
        
        
        for(int i = 0; i < vecBicicleta.length ; i++){
            if(vecBicicleta[i]==null){
                Consumidor cBicicleta = new Consumidor(vecTiempo,vec[16],piezaRueda,piezaMarco,piezaBicicleta,dBici,semRueda,bufferRueda,mutexRueda,semMar,bufferMar,mutexMar,"bicicleta",marco,rueda);
                vecBicicleta[i] = cBicicleta;
                vecBicicleta[i].start();
                break;
                }
        }
        int cont = vec[15]+1;
        vec[15] = vec[15] + 1;
        String cantidad = String.valueOf(cont);
        textBici.setText(cantidad);
    
    }
    }//GEN-LAST:event_agregarBicicletaActionPerformed

    private void agregarRuedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRuedaActionPerformed
       
        if(vec[9] < vec[13]){
        
        for(int i = 0; i < vecRueda.length ; i ++){
            if(vecRueda[i]==null){
            Mixto mixRueda = new Mixto(piezaBuje,piezaNeumatico,piezaRueda,semNeu, bufferNeu, mutexNeu, semBuje, bufferBuje, mutexBuje, semRueda, bufferRueda, mutexRueda, rueda, neumatico, buje, dRueda,"rueda");
            vecRueda[i] = mixRueda;
            vecRueda[i].start();
            break;
            }
        }
            int cont = vec[9] + 1;
            vec[9] = vec[9] + 1;
            String cantidad = String.valueOf(cont);
            textRueda.setText(cantidad);
        }
    }//GEN-LAST:event_agregarRuedaActionPerformed

    private void agregarTricicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTricicloActionPerformed
    if(vec[17] < vec[18]){
        
        if(cond2 == true){
            Tiempo t = new Tiempo(tiempoTriciclo,tiempo);
            vecTiempo[1] = t;
            vecTiempo[1].start();
            cond2 = false;
        }
        
        for(int i = 0 ;i < vecTriciclo.length ; i++){
        if(vecTriciclo[i] == null){
            Consumidor cTriciclo = new Consumidor(vecTiempo,vec[18],piezaRueda,piezaMarco,piezaTriciclo,dTriciclo,semRueda,bufferRueda,mutexRueda,semMar,bufferMar,mutexMar,"triciclo",marco,rueda);
            vecTriciclo[i] = cTriciclo;
            vecTriciclo[i].start();
            break;
                    }
                 }
        
        int cont = vec[16] + 1;
        vec[16] = vec[16] +1;
        String cantidad = String.valueOf(cont);
        textTriciclo.setText(cantidad);
        }
    }//GEN-LAST:event_agregarTricicloActionPerformed

    private void despedirNeumaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirNeumaticoActionPerformed
if(vec[7]>0){        
        for(int i = 0 ; i < vecNeumatico.length ; i++){
            if(vecNeumatico[i]!=null){
                if(vecNeumatico[i].isCondicion()){
                    vecNeumatico[i].setCondicion(false);
                    vecNeumatico[i] = null;
                    break;
                }
            }
        }
        int cont = vec[7]- 1;
        vec[7] = vec[7] - 1;
        String cantidad = String.valueOf(cont);
        textNeumatico.setText(cantidad);
}

    }//GEN-LAST:event_despedirNeumaticoActionPerformed

    private void despedirBujeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirBujeActionPerformed
     
        if(vec[8]>0){        
        for(int i = 0 ; i < vecBuje.length ; i++){
            if(vecBuje[i]!=null){
                if(vecBuje[i].isCondicion()){
                    vecBuje[i].setCondicion(false);
                    vecBuje[i]=null;
                    break;
                }
            }
        }
        
        int cont = vec[8] - 1;
        vec[8] = vec[8] - 1;
        String cantidad = String.valueOf(cont);
        textBuje.setText(cantidad);
        
        
        }       
    }//GEN-LAST:event_despedirBujeActionPerformed

    private void despedirRuedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirRuedaActionPerformed
       if(vec[9]>0){        
        for(int i = 0 ; i < vecRueda.length ; i++){
            if(vecRueda[i]!=null){
                if(vecRueda[i].isCondicion()){
                    vecRueda[i].setCondicion(false);
                    vecRueda[i] = null;
                    break;
                }
            }
        }
        
        int cont = vec[9] - 1;
        vec[9] = vec[9] - 1;
        String cantidad = String.valueOf(cont);
        textRueda.setText(cantidad);
}
    }//GEN-LAST:event_despedirRuedaActionPerformed

    private void despedirMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirMarcoActionPerformed
        if(vec[10]>0){        
        for(int i = 0 ; i < vecMarco.length ; i++){
            if(vecMarco[i]!=null){
                if(vecMarco[i].isCondicion()){
                    vecMarco[i].setCondicion(false);
                    vecMarco[i]=null;
                    break;
                }
            }
        }
        
        int cont = vec[10]- 1;
        vec[10] = vec[10] - 1;
        String cantidad = String.valueOf(cont);
        textMarco.setText(cantidad);
}
    }//GEN-LAST:event_despedirMarcoActionPerformed

    private void despedirBicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirBicicletaActionPerformed
        if(vec[15]>0){        
        for(int i = 0 ; i < vecBicicleta.length ; i++){
            if(vecBicicleta[i]!=null){
                if(vecBicicleta[i].isCondicion()){
                    vecBicicleta[i].setCondicion(false);
                    vecBicicleta[i]=null;
                    break;
                }
            }
        }
        
        int cont = vec[15] - 1;
        vec[15] = vec[15] - 1;
        String cantidad = String.valueOf(cont);
        textBici.setText(cantidad);
}
    }//GEN-LAST:event_despedirBicicletaActionPerformed

    private void despedirTricicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirTricicloActionPerformed
         if(vec[16]>0){        
        for(int i = 0 ; i < vecTriciclo.length ; i++){
            if(vecTriciclo[i]!=null){
                if(vecTriciclo[i].isCondicion()){
                    vecTriciclo[i].setCondicion(false);
                    vecTriciclo[i]=null;
                    break;
                }
            }
        }
        
        int cont = vec[16] - 1;
        vec[16] = vec[16] - 1;
        String cantidad = String.valueOf(cont);
        textTriciclo.setText(cantidad);
}
    }//GEN-LAST:event_despedirTricicloActionPerformed

    //Boton que ejecuta el inicio del programa
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        
         Tiempo t = new Tiempo(tiempoGlobal,vec[0]);
        t.start();
    
        
        //Se inician los hilos de Neumaticos
        int cant = vec[7];
        textNeumatico.setText(String.valueOf(cant));
        int cont = 0;
        for(int i = 0; i < vecNeumatico.length; i ++){
            if(cont<cant){
                Productor pNeumatico = new Productor(piezaNeumatico,neumatico,bufferNeu,semNeu,mutexNeu,"neumatico",dNeumatico);
                vecNeumatico[i] = pNeumatico;
                vecNeumatico[i].start();
                cont++;
            }
            
        }
        //Se inician los hilos de Bujes
        int cant2 = vec[8];
        textBuje.setText(String.valueOf(cant2));
        int cont2 = 0;
        for(int i = 0; i < vecBuje.length; i ++){
            if(cont2<cant2){
                Productor pBuje = new Productor(piezaBuje,buje,bufferBuje,semBuje,mutexBuje,"buje",dBuje);
                vecBuje[i] = pBuje;
                vecBuje[i].start();
                cont2++;
            }
            
        }
        
        //Se inician los hilos de Ruedas
        int cant3 = vec[9];
        textRueda.setText(String.valueOf(cant3));
        int cont3 = 0;
        for(int i = 0; i < vecRueda.length; i ++){
            if(cont3<cant3){
                Mixto pRueda = new Mixto(piezaBuje,piezaNeumatico,piezaRueda,semNeu, bufferNeu, mutexNeu, semBuje, bufferBuje, mutexBuje, semRueda, bufferRueda, mutexRueda, rueda, neumatico, buje, dRueda,"rueda");
                vecRueda[i] = pRueda;
                vecRueda[i].start();
                cont3++;
            }
            
        }
        
        //Se inician los hilos de Marcos
        int cant4 = vec[10];
        textMarco.setText(String.valueOf(cant4));
        int cont4 = 0;
        for(int i = 0; i < vecMarco.length; i ++){
            if(cont4<cant4){
                Productor pMarco = new Productor(piezaMarco,marco,bufferMar,semMar,mutexMar,"marco",dMarco);
                vecMarco[i] = pMarco;
                vecMarco[i].start();
                cont4++;
            }
            
        }
        
        //Se inician los hilos de Bicicletas
        int cant5 = vec[15];
        textBici.setText(String.valueOf(cant5));
        if(cond == true){
            Tiempo t1 = new Tiempo(tiempoBici,tiempo);
            vecTiempo[0] = t1;
            vecTiempo[0].start();
            cond = false;
        }
        int cont5 = 0;
        for(int i = 0; i < vecBicicleta.length; i ++){
            if(cont5<cant5){
                Consumidor cBici = new Consumidor(vecTiempo,vec[1],piezaRueda,piezaMarco,piezaBicicleta,dBici,semRueda,bufferRueda,mutexRueda,semMar,bufferMar,mutexMar,"bicicleta",marco,rueda);
                vecBicicleta[i] = cBici;
                vecBicicleta[i].start();
                cont5++;
            }
            
        }
        
        //Se inician los hilos de Triciclos
        int cant6 = vec[17];
        textTriciclo.setText(String.valueOf(cant6));
        int cont6 = 0;
        if(cond2 == true){
            Tiempo t2 = new Tiempo(tiempoTriciclo,tiempo);
            vecTiempo[1] = t2;
            vecTiempo[1].start();
            cond2 = false;
        }
        
        for(int i = 0; i < vecTriciclo.length; i ++){
            if(cont6<cant6){
                Consumidor cTriciclo = new Consumidor(vecTiempo,vec[2],piezaRueda,piezaMarco,piezaTriciclo,dTriciclo,semRueda,bufferRueda,mutexRueda,semMar,bufferMar,mutexMar,"triciclo",marco,rueda);
                vecTriciclo[i] = cTriciclo;
                vecTriciclo[i].start();
                cont6++;
            }
            
        }
        
       
        
       
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Archivo a = new Archivo();
                vec = a.Leer();

                new Interfaz().setVisible(true);
            }
        });
        
     
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBicicleta;
    private javax.swing.JButton agregarBuje;
    private javax.swing.JButton agregarMarco;
    private javax.swing.JButton agregarNeumatico;
    private javax.swing.JButton agregarRueda;
    private javax.swing.JButton agregarTriciclo;
    private javax.swing.JButton despedirBicicleta;
    private javax.swing.JButton despedirBuje;
    private javax.swing.JButton despedirMarco;
    private javax.swing.JButton despedirNeumatico;
    private javax.swing.JButton despedirRueda;
    private javax.swing.JButton despedirTriciclo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pausaBici;
    private javax.swing.JButton pausaBuje;
    private javax.swing.JButton pausaMarco;
    private javax.swing.JButton pausaNeu;
    private javax.swing.JButton pausaRueda;
    private javax.swing.JButton pausaTriciclo;
    private javax.swing.JTextField piezaBicicleta;
    private javax.swing.JTextField piezaBuje;
    private javax.swing.JTextField piezaMarco;
    private javax.swing.JTextField piezaNeumatico;
    private javax.swing.JTextField piezaRueda;
    private javax.swing.JTextField piezaTriciclo;
    private javax.swing.JButton playBici;
    private javax.swing.JButton playBuje;
    private javax.swing.JButton playMarco;
    private javax.swing.JButton playNeu;
    private javax.swing.JButton playRueda;
    private javax.swing.JButton playTriciclo;
    private javax.swing.JButton start;
    private javax.swing.JTextField textBici;
    private javax.swing.JTextField textBuje;
    private javax.swing.JTextField textMarco;
    private javax.swing.JTextField textNeumatico;
    private javax.swing.JTextField textRueda;
    private javax.swing.JTextField textTriciclo;
    private javax.swing.JTextField tiempoBici;
    private javax.swing.JTextField tiempoGlobal;
    private javax.swing.JTextField tiempoTriciclo;
    // End of variables declaration//GEN-END:variables
}
